ls:
  .browser.spec.ts: kebab-case
  .config.browser.ts: kebab-case
  .config.neutral.ts: kebab-case
  .config.node.ts: kebab-case
  .config.ts: kebab-case
  .d.json.ts: kebab-case
  .d.ts: kebab-case
  .node.spec.ts: kebab-case
  .spec.ts: kebab-case
  .ts: kebab-case
  .vue: kebab-case
  .workspace.ts: kebab-case

ignore:
  - .git
  - .github
  - coverage
  - dist
  - lib
  - node_modules
  - packages
