version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
      time: '07:00'
      timezone: GMT
    labels:
      - 'dependencies'
      - 'github-actions'
  - package-ecosystem: pip
    directory: '/packages/container'
    schedule:
      interval: weekly
      day: saturday
      time: '07:00'
      timezone: GMT
    open-pull-requests-limit: 10
    commit-message:
      prefix: fix
      include: scope
