name: ci

on:
  pull_request:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE
  push:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE

permissions:
  contents: read
  packages: read

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  context:
    uses: escapace/workflows/.github/workflows/context.yaml@trunk

  ci-typescript:
    needs:
      - context
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    uses: escapace/workflows/.github/workflows/ci-typescript.yaml@trunk
    with:
      enable-artifact-upload: true
      enable-codecov: true
      node-version: ${{ needs.context.outputs.node-version }}
      pnpm-version: ${{ needs.context.outputs.pnpm-version }}
      ref: ${{ needs.context.outputs.ref }}
      version: ${{ needs.context.outputs.version }}

  ci-container:
    needs:
      - context
      - ci
    uses: escapace/workflows/.github/workflows/ci-container.yaml@trunk
    with:
      build-args: |
        NODE_VERSION=${{ needs.context.outputs.node-version }}
        PNPM_VERSION=${{ needs.context.outputs.pnpm-version }}
      enable-push: false
      latest: ${{ fromJSON(needs.context.outputs.latest) }}
      platforms: linux/amd64,linux/arm64
      prerelease: ${{ fromJSON(needs.context.outputs.prerelease) }}
      version: ${{ needs.context.outputs.version }}
