name: ci

on:
  push:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE
  pull_request:
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE

permissions:
  contents: read
  packages: read

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

jobs:
  context:
    uses: ./.github/workflows/workflow-call-context.yaml
  ci:
    uses: ./.github/workflows/workflow-call-ci.yaml
    needs:
      - context
    with:
      ref: ${{ needs.context.outputs.ref }}
      node-version: ${{ needs.context.outputs.node-version }}
      pnpm-version: ${{ needs.context.outputs.pnpm-version }}
      version: ${{ needs.context.outputs.version }}
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  build-container:
    needs:
      - context
      - ci
    uses: ./.github/workflows/workflow-call-build-container.yaml
    with:
      push: false
      platforms: linux/amd64,linux/arm64
      file: 'package/packages/container/Dockerfile'
      context: 'lib/satie-${{ needs.context.outputs.version }}.tgz'
      annotations: ${{ needs.context.outputs.docker-metadata-annotations }}
      labels: ${{ needs.context.outputs.docker-metadata-labels }}
      tags: ${{ needs.context.outputs.docker-metadata-tags }}
      build-args: |
        NODE_VERSION=${{ needs.context.outputs.node-version }}
        PNPM_VERSION=${{ needs.context.outputs.pnpm-version }}
