name: release

on:
  push:
    tags:
      - 'v*'

env:
  # 7 GiB by default on GitHub, setting to 6 GiB
  # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
  NODE_OPTIONS: --max-old-space-size=6144

permissions:
  contents: read
  packages: read

jobs:
  context:
    uses: escapace/workflows/.github/workflows/context.yaml@trunk

  ci-typescript:
    if: needs.context.outputs.environment == 'production' || needs.context.outputs.environment == 'staging'
    needs:
      - context
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    uses: escapace/workflows/.github/workflows/ci-typescript.yaml@trunk
    with:
      enable-artifact-upload: true
      enable-codecov: ${{ !github.event.repository.private }}
      node-version: ${{ needs.context.outputs.node-version }}
      pnpm-version: ${{ needs.context.outputs.pnpm-version }}
      ref: ${{ needs.context.outputs.ref }}
      version: ${{ needs.context.outputs.version }}

  release-container:
    needs:
      - context
      - ci-typescript
    permissions:
      attestations: write
      id-token: write
      packages: write
    uses: escapace/workflows/.github/workflows/release-container.yaml@trunk
    with:
      build-args: |
        NODE_VERSION=${{ needs.context.outputs.node-version }}
        PNPM_VERSION=${{ needs.context.outputs.pnpm-version }}
      enable-build-provenance-attestation: ${{ !github.event.repository.private && (needs.context.outputs.environment == 'production' || needs.context.outputs.environment == 'staging') }}
      enable-cosign: ${{ github.event.repository.private && (needs.context.outputs.environment == 'production' || needs.context.outputs.environment == 'staging') }}
      enable-push: ${{ needs.context.outputs.environment == 'production' || needs.context.outputs.environment == 'staging' }}
      latest: ${{ fromJSON(needs.context.outputs.latest) }}
      platforms: linux/amd64,linux/arm64
      prerelease: ${{ fromJSON(needs.context.outputs.prerelease) }}
      version: ${{ needs.context.outputs.version }}

  release-typescript:
    if: needs.context.outputs.environment == 'production' || needs.context.outputs.environment == 'staging'
    needs:
      - context
      - ci-typescript
      - release-container
    permissions:
      id-token: write
      packages: write
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    uses: escapace/workflows/.github/workflows/release-typescript.yaml@trunk
    with:
      node-version: ${{ needs.context.outputs.node-version }}

  release-github:
    if: needs.context.outputs.environment == 'production' || needs.context.outputs.environment == 'staging'
    needs:
      - context
      - ci-typescript
      - release-container
      - release-typescript
    permissions:
      contents: write
    uses: escapace/workflows/.github/workflows/release-github.yaml@trunk
    with:
      changelog: ${{ needs.context.outputs.changelog }}
      prerelease: ${{ fromJSON(needs.context.outputs.prerelease) }}
      version: ${{ needs.context.outputs.version }}
