name: release

on:
  push:
    tags:
      - 'v*'
    branches:
      - trunk
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  context:
    uses: ./.github/workflows/workflow-call-context.yaml
  test-build:
    needs:
      - context
    uses: ./.github/workflows/workflow-call-test-build.yaml
    with:
      ref: ${{ needs.context.outputs.ref }}
      node-version: ${{ needs.context.outputs.node-version }}
      pnpm-version: ${{ needs.context.outputs.pnpm-version }}
      artifact-name: ${{ needs.context.outputs.version }}
  build-container:
    needs:
      - context
      - test-build
    if: needs.context.outputs.environment == 'production'
    uses: ./.github/workflows/workflow-call-build-container.yaml
    concurrency: ${{ github.ref }}
    with:
      artifact-name: ${{ needs.context.outputs.version }}
      file: Dockerfile
      args: >-
        --tag ghcr.io/${{ github.repository }}:${{ needs.context.outputs.version }}
  github-release:
    needs:
      - context
      - build-container
    if: needs.build-container.result == 'success'
    uses: ./.github/workflows/workflow-call-github-release.yaml
    with:
      environment: ${{ needs.context.outputs.environment }}
      node-version: ${{ needs.context.outputs.node-version }}
      pnpm-version: ${{ needs.context.outputs.pnpm-version }}
      ref: ${{ needs.context.outputs.ref }}
