on:
  workflow_call:
    outputs:
      changelog:
        description: 'short github sha'
        value: ${{ jobs.main.outputs.changelog }}
      commitish:
        description: 'short github sha'
        value: ${{ jobs.main.outputs.commitish }}
      environment:
        description: 'version'
        value: ${{ jobs.main.outputs.environment }}
      node-version:
        description: 'node.js version'
        value: ${{ jobs.main.outputs.node-version }}
      pnpm-version:
        description: 'pnpm version'
        value: ${{ jobs.main.outputs.pnpm-version }}
      prerelease:
        description: 'is prerelease'
        value: ${{ jobs.main.outputs.prerelease }}
      ref:
        description: 'ref'
        value: ${{ jobs.main.outputs.ref }}
      version:
        description: 'version'
        value: ${{ jobs.main.outputs.version }}
      docker-metadata-tags:
        description: 'docker tags'
        value: ${{ jobs.main.outputs.docker-metadata-tags }}
      docker-metadata-annotations:
        description: 'docker annotations'
        value: ${{ jobs.main.outputs.docker-metadata-annotations }}
      docker-metadata-labels:
        description: 'docker labels'
        value: ${{ jobs.main.outputs.docker-metadata-labels }}
      docker-metadata-json:
        description: 'json output of docker tags and labels'
        value: ${{ jobs.main.outputs.docker-metadata-json }}
jobs:
  main:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.action-context.outputs.changelog }}
      commitish: ${{ steps.action-context.outputs.commitish }}
      environment: ${{ steps.action-context.outputs.environment }}
      node-version: ${{ steps.node-version.outputs.value }}
      pnpm-version: ${{ steps.pnpm-version.outputs.value }}
      prerelease: ${{ fromJSON(steps.action-context.outputs.prerelease) }}
      ref: ${{ steps.ref.outputs.value }}
      version: ${{ steps.action-context.outputs.version }}
      docker-metadata-tags: ${{ steps.docker-metadata.outputs.tags }}
      docker-metadata-annotations: ${{ steps.docker-metadata.outputs.annotations }}
      docker-metadata-labels: ${{ steps.docker-metadata.outputs.labels }}
      docker-metadata-json: ${{ steps.docker-metadata.outputs.json }}
    steps:
      - id: ref
        name: ref
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "value=${GITHUB_HEAD_REF}" >> $GITHUB_OUTPUT
          else
            echo "value=${GITHUB_REF}" >> $GITHUB_OUTPUT
          fi
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.ref.outputs.value }}
          fetch-depth: 0
      - id: action-context
        uses: escapace/action-context@v0.8.0
        with:
          token: ${{ github.token }}
      - name: docker meta
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          context: git
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable={{is_default_branch}}
      - id: node-version
        name: node-version
        shell: bash
        run: |
          echo "value=$(cat package.json | jq -r .engines.node | grep -oP '([0-9]+)\.([0-9]+)\.([0-9]+)' | head -n 1)"  >> $GITHUB_OUTPUT
      - id: pnpm-version
        name: pnpm-version
        shell: bash
        run: |
          echo "value=$(cat package.json | jq -r .engines.pnpm | grep -oP '([0-9]+)\.([0-9]+)\.([0-9]+)' | head -n 1)" >> $GITHUB_OUTPUT
